apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
  - name: body
    value: $(body)
  - name: title
    value: $(body.title)
  - name: link
    value: $(body.link)
  - name: contenttype
    value: $(header.Content-Type)
