apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: tekton-pipelines
spec:
  taskRef:
    name: create-webhook
  params:
  # - name: GitHubOrg
  #   value: "iancoffey"
  - name: GitHubUser
    value: "cmwylie19"
  - name: GitHubRepo
    value: "task-mongo"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: token
  - name: GitHubSecretStringKey
    value: secret
  # - name: ExternalDomain
  #   value: demo.iancoffey.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
