
settings:
  create: true
  watchNamespaces:
  - default
gloo:
  deployment:
    externalTrafficPolicy: Local
    # gatewayProxies:
    #   gateway-proxy:
    #     gatewaySettings: 
    #       customHttpGateway:
    stats: enabled
    gateway:
      validation:
        alwaysAcceptResources: false
    gatewayProxies:
      gatewayProxy:
        service:
          externalTrafficPolicy: Local
grafana: # The grafana settings can be removed for Gloo Edge OSS
  rbac:
    namespaced: true