apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oidc-dex
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        app_url: http://localhost:8000/
        callback_path: /get
        client_id: gloo
        client_secret_ref:
          name: oauth
          namespace: gloo-system
        issuer_url: http://dex.gloo-system.svc.cluster.local:32000/
        scopes:
        - email
        session:
          cookieOptions:
            notSecure: true
            maxAge: 360
          failOnFetchFailure: true
          redis:
            cookieName: cookie
            options:
              host: redis.gloo-system.svc.cluster.local:6379
        logoutPath: /auth/logout