apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: db-policy
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: remote_address
      rateLimit:
        requestsPerUnit: 3
        unit: MINUTE
    rateLimits:
    - actions:
      - remoteAddress: {}