apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: default
  namespace: gloo-system
spec:
  routes:
    - matchers:
        - prefix: /tasks
      routeAction:
        single:
          upstream:
            name: default-task-8080
            namespace: gloo-system

                