apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-task-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      app: task
  kube:
    selector:
      app: task
    serviceName: task
    serviceNamespace: default
    servicePort: 8080