apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    # options:
    #   stagedTransformations:
    #     early:
    #       requestTransforms:
    #         - requestTransformation:
    #             transformationTemplate:
    #               extractors:
    #                 token:
    #                   header: 'cookie'
    #                   regex: 'id_token=(.*); .*'
    #                   subgroup: 1
    #               headers:
    #                 jwt:
    #                   text: '{{ token }}'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          kube:
            ref:
              name: petstore
              namespace: default
            port: 8080

    # options:
    #   extauth:
    #     configRef:
    #       name: oidc-dex
    #       namespace: gloo-system