apiVersion: devportal.solo.io/v1alpha1
kind: Portal
metadata:
  name: task-portal
  namespace: default
spec:
  displayName: Task Portal
  description: The Gloo Portal for the Task API
  banner:
    fetchUrl: https://i.imgur.com/YSJCQZY.png
  favicon:
    fetchUrl: https://i.imgur.com/YSJCQZY.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/YSJCQZY.png
  customStyling: {}
  staticPages: []

  domains:
  # If you are using Gloo Edge and the Gateway is listening on a port other than 80, 
  # you need to include a domain in this format: <DOMAIN>:<PORT>.
  # In this example we expect the Gateway to listen on port 32000.
  - task.example.com:32000
  - task.example.com

  # This will include all API product of the environment in the portal
  publishedEnvironments:
  - name: dev
    namespace: default